export { default as DashboardLayout } from './DashboardLayout';
export { default as Admin } from './Admin';
export { default as AllCharacters } from './AllCharacters';
export { default as FavoriteCharacters } from './FavoriteCharacters';
export { default as Error} from './Error';
export { default as HomeLayout } from './HomeLayout';
export { default as Landing } from './Landing';
export { default as Login } from './Login';
export { default as Profile} from './Profile';
export { default as Register } from './Register';
